# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'kissXML' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kissXML
     pod 'KissXML', '~> 5.0.3'


end
