# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '发短信' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 发短信
   pod 'MBProgressHUD', '~> 0.9.2'

end
